### ISSUE TITLE
The MAC Address is always AA:AA:AA:AA:AA:AA

### ISSUE THREAD

**Issue by A-Small-Mice** [rodneyknaap/atx-turboxt-v3#4]
![issue (2)](https://github.com/user-attachments/assets/954226a3-036f-4f85-b662-331487def223)
![issue (1)](https://github.com/user-attachments/assets/6d3e9ca3-97b6-4026-add1-4ba8698cc7bb)

I was deeply impressed by your project, so I created my own ATX Turbo XT motherboard. There are still a few important issues, but the one that concerns me the most is the LAN problem. I used the dump image of the 9346 chip you provided, but the MAC address shows up as **AA:AA:AA:AA:AA**, and the DHCP server is not connecting. When I remove the 9346 chip from the motherboard, the MAC address becomes **00:00:00:00:00:00**. What should I do?

**Comment by A-Small-Mice** [comment]
I've learned a lesson that I shouldn't attempt anything when I'm tired. The cause was too simple: incorrect I/O address assignment.

**Comment by rodneyknaap** [comment]
Hi A-Small-Mice, thanks for sharing a photo of the system. It's the first build photo I have seen so far. The system took countless hours to design and develop in my spare time so it's nice to see someone else attempting to build this. No problem that you shared this issue because by doing so you also created a solution in case someone else observed this behavior from the Realtek chip. Remember, I have already built and tested this whole system and found no further issues on the prototype. Having said that, there are of course no guarantees! But still, I love to get some information how others fared in building the system! Wish you good luck on your work!

**Comment by A-Small-Mice** [comment]
Thank you sincerely for sharing this wonderful project that allowed me to build it. I have wanted an XT motherboard made in the ATX form factor **without using a motherboard chipset** for a long time, and you’ve made my dream come true. The best I can do to express my gratitude is to show you how well I am using this amazing project. Here are a few more photos of the ATX XT that I built...

![atx_xt (1)](https://github.com/user-attachments/assets/2dedf305-3253-434b-bf67-f3a97753bcb5)
![atx_xt (2)](https://github.com/user-attachments/assets/9587a8ba-6a9a-45cc-8cc0-19f3b47a5406)
![atx_xt (5)](https://github.com/user-attachments/assets/79359449-c6ba-4b0d-8e0a-eeb0311e7e72)
![atx_xt (4)](https://github.com/user-attachments/assets/5048d76d-8fed-4dc1-b542-68c84e62fc78)
![atx_xt (6)](https://github.com/user-attachments/assets/787ba19f-f7ef-4936-9f04-f681fbd324b6)

And there is enough space in the 128KB ROM to fit 32KB of ROM BASIC, so I created the system ROM as follows:

`copy /b blank8k.bin + floppy22_144_360.bin + ide_xt.bin + CAS_U29.bin + CAS_U30.bin + CAS_U31.bin + CAS_U32.bin + pcxtbios.bin xt_64kb.bin`

`copy /b xt_64kb.bin + xt_64kb.bin xt_128kb.bin`

![basic](https://github.com/user-attachments/assets/ba9acd4f-9449-4aba-acb6-a18b6b2947d8)

**Comment by rodneyknaap** [comment]
Hi A-Small-Mice,

A very beautiful build! I particularly love the red/brown color bypass capacitors, they have a beautiful contrast with your black solder mask mainboard, a great combination and old school effect in your build. 

And my compliments on the HDD front you used with the very old school looking HDD LED inside it.
This also brings a original legacy feeling to your build when seeing it.
The Cooler Master case also looks really great.

My congratulations on this great system, I really love how it turned out!
After not using my XT build for a while, when I power it on again, I enjoy the experience every time.
The XT is simply a charming system. :)

A very nice suggestion about the BASIC ROM, thanks for sharing this, I also should try this out.

Thanks for sharing these additional photos, I much appreciate it!

Kind regards,

Rodney
